name = "glats"
version = "0.7.0"
description = "A NATS client for Gleam."

licences = ["MIT"]
repository = { type = "github", user = "arnarg", repo = "glats" }
gleam = ">= 0.32.0"

[dependencies]
gleam_stdlib = "~> 0.36"
gnat = "~> 1.8"
gleam_erlang = "~> 0.25"
gleam_otp = "~> 0.10"
gleam_json = "~> 1.0"
gleam_crypto = "~> 1.3"

[dev-dependencies]
gleeunit = "~> 1.0"
